modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"

    logoFile="${mod_id}.png"
    credits="${mod_credits}"
    authors = "${mod_author}"
    description = '''${mod_description}'''

[[mixins]]
    config = "${mod_id}.mixins.json"

[[mixins]]
    config = "${mod_id}.neoforge.mixins.json"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    mandatory = true
    versionRange = "${neoforge_loader_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"